### ISSUE TITLE
Default Boot to USB

### ISSUE THREAD

**Issue by Anklum** [Chriskt78/rEFInd-Chriskt78#2]
Hi,

I have a question about your project.
Could it be possible to default boot on USB if present and another system if not?

I explain : I would like to boot on USB (Recalbox) if the key is present and Windows if not
I could only change boot order on BIOS but this one have identification issues : USB key is not recognized anymore if I boot on another system until I go back to BIOS and validate it again... Computer Support cannot help me and says their BIOS acts like this by design.

A solution I found was to use your refind project to boot on USB or WINDOWS without going back to BIOS.
It looks actually configured to boot on the last system launched
It would be perfect to me if it could always boot on USB if present, and Windows if not (computer is plugged on tv, keyboard is not always accessible)

Do you think if could be possible? And if so what would I have to change?

Thanks for your work  !

**Comment by Anklum** [comment]
after a few test, I think I found what I wanted! I added
default_selection recalbox
in refind.conf file
And uninstalled / reinstalled to copy changes to EFI partition.
Then it's exactly what I wanted : refind boots on USB automatically if usb key is connected, and if not it boots on the first one : Windows

**Comment by Chriskt78** [comment]
Sorry for the delayed answer, I'm not really active on Github ;)

Great you find the good configuration.
Personally, I prefer standard usage of Refind, boot to last selected OS. But you found how to select default selection.

Happy my personal project helped you.
Cheers
